# Generated by Django 5.0 on 2023-12-05 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polyclinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_department', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель отделения'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis', to='polyclinic.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_histories', to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
    ]
