# Generated by Django 5.0 on 2023-12-05 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='rooms_qty',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='treatment_time',
            field=models.DateField(blank=True, default=0, verbose_name='Время на лечение'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis', to='polyclinic.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_histories', to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
    ]
